main: nl.lucasridder.java.Main
name: Hub
version: 1.3
author: LucasRidder
api-version: 1.15

commands:
 gamemode:
  aliases: gm
  usage: "Usage: /<command> [survival|creative|adventure|spectator|0|1|2|3] ([player])"
 fly:
  usage: "/<command>"
 survival:
  usage: "/<command>"
 minigames:
  usage: "/<command>"
 pixelmon:
  usage: "/<command>"
 setspawn:
  usage: "/<command>"
 lock:
  aliases: lockdown
  usage: "/<command> (reden)"