main: nl.lucasridder.java.Main
name: Hub
version: 1.3
author: LucasRidder
api-version: 1.16

commands:
 gamemode:
  aliases: gm
  usage: "Usage: /<command> [survival|creative|adventure|spectator|0|1|2|3] ([player])"
 survival:
  usage: "/<command>"
 minigames:
  usage: "/<command>"
 kitpvp:
  usage: "/<command>"
 setspawn:
  usage: "/<command>"
 stop:
  usage: "/<command>"
 staff:
   usage: "/<command>"
 vanish:
  aliases: v
  usage: "/<command>"